spring.application.name=tool-server
server.port=8080

# spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring.main.banner-mode=off
# logging.pattern.console=

# spring.ai.mcp.server.stdio=false

spring.ai.mcp.server.name=tool-server
spring.ai.mcp.server.version=0.0.1

#spring.ai.mcp.server.protocol=STREAMABLE
#spring.ai.mcp.server.request-timeout=1h

#logging.file.name=C:/Development/Projects/AI/Spring/spring-ai-mcp-toolsserver.log
